### ISSUE TITLE
EOF should quick rexster console

### ISSUE THREAD

**Issue by nik9000** [tinkerpop/gremlin#385]
I'm not sure of the right way to say this now that TinkerPop3 is out and all the names changed but ctrl-D/EOF should really quit the rexster console.  You should be able to pipe scripts to it and it should just quit when it finishes reading them rather than spitting out null over and over again.  And ctrl-D is the normal way of quitting things like psql/mysql so its surprising that it doesn't work.

**Comment by spmallette** [comment]
It doesn't sound like this is a "gremlin" issue (i.e. related to gremlin.sh), so I assume it doesn't belong here.  If this is a rexster console issue (i.e. related to rexster-console.sh), then it should go here: https://github.com/tinkerpop/rexster/issues

If you migrate the issue to Rexster, please keep in mind that I don't completely follow the problem based on your description, so please restate/elaborate a bit as you create the new issue in Rexster.  I'm only guessing but it sounds like you're talking about problems related to usage of `-e`?

Unless I've grossly misunderstood something, I don't think this issue is meant to be here, so I'll close for now on the assumption you'll have a new issue over in Rexster at some point soon.

**Comment by nik9000** [comment]
Ah!  I thought you merged the projects into one with TP3.  I'll go there.

**Comment by nik9000** [comment]
Moved to https://github.com/tinkerpop/rexster/issues/380.

**Comment by spmallette** [comment]
no - TP3 is a full re-write.  we only brought over the spirit of the individual projects into it.  TP2 projects will continue where they are in long-term maintenance mode.  thanks for moving the issue.
